# Generated by Django 5.2.6 on 2025-11-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('reports', '0003_comentarioreporte_comment_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comentario',
            field=models.ForeignKey(blank=True, db_column='comentario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='reports.comentarioreporte', verbose_name='Comentario relacionado'),
        ),
    ]
