# Generated by Django 5.2.6 on 2025-11-19 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
        ('notifications', '0002_notification_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=500, unique=True, verbose_name='Token de Push')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, verbose_name='Plataforma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='entities.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Push',
                'verbose_name_plural': 'Tokens de Push',
                'db_table': 'push_tokens',
                'indexes': [models.Index(fields=['usuario', 'is_active'], name='push_tokens_usuario_7ecd8d_idx'), models.Index(fields=['push_token'], name='push_tokens_push_to_6c254b_idx')],
            },
        ),
    ]
