# Generated by Django 5.2.6 on 2025-09-28 10:08

import django.db.models.deletion
import domain.entities.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('rous_id', models.AutoField(primary_key=True, serialize=False)),
                ('rous_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usua_id', models.IntegerField(default=domain.entities.usuario.generate_user_id, primary_key=True, serialize=False)),
                ('usua_rut', models.CharField(max_length=12, unique=True)),
                ('usua_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('usua_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('usua_nickname', models.CharField(max_length=50, unique=True)),
                ('usua_email', models.EmailField(max_length=254)),
                ('usua_pass', models.CharField(max_length=128)),
                ('usua_creado', models.DateTimeField(auto_now_add=True)),
                ('usua_actualizado', models.DateTimeField(blank=True, null=True)),
                ('usua_telefono', models.BigIntegerField()),
                ('usua_estado', models.IntegerField(choices=[(0, 'Deshabilitado'), (1, 'Habilitado')], default=1)),
                ('rous_id', models.ForeignKey(db_column='rous_id', on_delete=django.db.models.deletion.CASCADE, to='entities.rolusuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='SesionToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_valor', models.CharField(max_length=255, unique=True)),
                ('token_creado_en', models.DateTimeField(auto_now_add=True)),
                ('token_expira_en', models.DateTimeField()),
                ('token_activo', models.BooleanField(default=True)),
                ('usua_id', models.ForeignKey(db_column='usua_id', on_delete=django.db.models.deletion.CASCADE, to='entities.usuario')),
            ],
            options={
                'verbose_name': 'Token de Sesión',
                'verbose_name_plural': 'Tokens de Sesión',
                'db_table': 'sesion_token',
            },
        ),
        migrations.CreateModel(
            name='RecuperarUsuario',
            fields=[
                ('reus_id', models.AutoField(primary_key=True, serialize=False)),
                ('reus_token', models.CharField(max_length=6)),
                ('reus_expira_en', models.DateTimeField()),
                ('reus_creado_en', models.DateTimeField(auto_now_add=True)),
                ('reus_usado', models.BooleanField(default=False)),
                ('usua_id', models.ForeignKey(db_column='usua_id', on_delete=django.db.models.deletion.CASCADE, to='entities.usuario')),
            ],
            options={
                'verbose_name': 'Recuperación de Usuario',
                'verbose_name_plural': 'Recuperaciones de Usuario',
                'db_table': 'recuperar_usuario',
            },
        ),
    ]
