# Generated by Django 5.2.6 on 2025-10-01 21:20

import domain.entities.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usua_id',
            field=models.AutoField(default=domain.entities.usuario.generate_user_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
