# Generated by Django 5.2.7 on 2025-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectomodel',
            name='proy_lugar',
            field=models.CharField(blank=True, db_column='proy_lugar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyectomodel',
            name='proy_tipo_denuncia',
            field=models.CharField(blank=True, db_column='proy_tipo_denuncia', max_length=100, null=True),
        ),
    ]
