# Generated by Django 5.2.6 on 2025-10-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        # Esta migración se deja vacía porque la tabla Proyecto no existe en la BD
        # Los cambios de schema se harán cuando la tabla sea creada correctamente
        # TODO: Recrear esta migración cuando la tabla Proyecto exista
    ]
