# Generated by Django 5.2.6 on 2025-10-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='DenunciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'denuncia_estados',
            },
        ),
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_denuncias',
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('ubicacion', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('urgencia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ciudad')),
                ('denuncia_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.denunciaestado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='entities.usuario')),
                ('tipo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.tipodenuncia')),
            ],
            options={
                'db_table': 'reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
