# Generated by Django 5.2.6 on 2025-10-21 02:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import reports.models.report_archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='DenunciaEstado',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'denuncia_estados',
            },
        ),
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_denuncias',
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('direccion', models.CharField(default='Dirección no especificada', max_length=255, verbose_name='Dirección')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Coordenadas geográficas del reporte', srid=4326, verbose_name='Ubicación geográfica')),
                ('visible', models.BooleanField(default=True)),
                ('urgencia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ciudad')),
                ('denuncia_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.denunciaestado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='entities.usuario')),
                ('tipo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.tipodenuncia')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VotoReporte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del voto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='reports.reportmodel', verbose_name='Reporte')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='votos_reportes', to='entities.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto de Reporte',
                'verbose_name_plural': 'Votos de Reportes',
                'db_table': 'voto_reporte',
                'ordering': ['-fecha_voto'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREATE', 'Creado'), ('UPDATE', 'Actualizado'), ('DELETE', 'Eliminado'), ('STATUS_CHANGE', 'Cambio de Estado'), ('URGENCY_CHANGE', 'Cambio de Urgencia'), ('IMAGE_ADD', 'Imagen Agregada'), ('IMAGE_DELETE', 'Imagen Eliminada')], max_length=20, verbose_name='Acción')),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_reportes', to='entities.usuario', verbose_name='Usuario que realizó la acción')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reports.reportmodel', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'db_table': 'report_history',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['reporte', '-fecha'], name='report_hist_reporte_996e1f_idx'), models.Index(fields=['usuario'], name='report_hist_usuario_2a390d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportArchivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(help_text='Archivo subido (imagen o video únicamente)', max_length=200, upload_to=reports.models.report_archivos.upload_to_report_files, verbose_name='Archivo')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo al momento de la subida', max_length=255, verbose_name='Nombre original')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=20, verbose_name='Tipo de archivo')),
                ('tamaño_bytes', models.PositiveBigIntegerField(default=0, help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en bytes')),
                ('extension', models.CharField(help_text='Extensión del archivo sin el punto (jpg, png, mp4, etc.)', max_length=10, verbose_name='Extensión')),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME del archivo (image/jpeg, video/mp4, etc.)', max_length=100, verbose_name='Tipo MIME')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización del archivo', verbose_name='Orden')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si este es el archivo principal del reporte', verbose_name='Es principal')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el archivo está activo', verbose_name='Activo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_actualizada', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('reporte', models.ForeignKey(help_text='Reporte al que pertenece este archivo', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reports.reportmodel', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Archivo de Reporte',
                'verbose_name_plural': 'Archivos de Reportes',
                'db_table': 'report_archivos',
                'ordering': ['orden', 'fecha_subida'],
                'indexes': [models.Index(fields=['reporte', 'activo'], name='report_arch_reporte_bd76d9_idx'), models.Index(fields=['tipo_archivo'], name='report_arch_tipo_ar_165495_idx'), models.Index(fields=['es_principal'], name='report_arch_es_prin_79fdec_idx'), models.Index(fields=['fecha_subida'], name='report_arch_fecha_s_ddd8c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('reporte',), name='unique_principal_per_reporte')],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReporte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='reports.reportmodel', verbose_name='Reporte')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_seguidos', to='entities.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de Reporte',
                'verbose_name_plural': 'Seguimientos de Reportes',
                'db_table': 'seguimiento_reporte',
                'ordering': ['-fecha_seguimiento'],
                'indexes': [models.Index(fields=['usuario', 'fecha_seguimiento'], name='seguimiento_usuario_f52b05_idx'), models.Index(fields=['reporte'], name='seguimiento_reporte_7332d6_idx')],
                'unique_together': {('usuario', 'reporte')},
            },
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['usuario', 'visible'], name='reportes_usuario_596e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['fecha_creacion'], name='reportes_fecha_c_2cef5a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['urgencia'], name='reportes_urgenci_a25701_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['denuncia_estado'], name='reportes_denunci_e86780_idx'),
        ),
        migrations.AddIndex(
            model_name='votoreporte',
            index=models.Index(fields=['usuario', 'fecha_voto'], name='voto_report_usuario_29e689_idx'),
        ),
        migrations.AddIndex(
            model_name='votoreporte',
            index=models.Index(fields=['reporte'], name='voto_report_reporte_2db064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votoreporte',
            unique_together={('usuario', 'reporte')},
        ),
    ]
