# Generated by Django 5.2.6 on 2025-10-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='DenunciaEstado',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'denuncia_estados',
            },
        ),
        migrations.CreateModel(
            name='ProyectoModel',
            fields=[
                ('proy_id', models.AutoField(db_column='proy_id', primary_key=True, serialize=False)),
                ('proy_titulo', models.CharField(db_column='proy_titulo', max_length=50)),
                ('proy_descripcion', models.TextField(db_column='proy_descripcion')),
                ('proy_estado', models.IntegerField(choices=[(1, 'Planificación'), (2, 'En Progreso'), (3, 'Completado'), (4, 'Cancelado'), (5, 'Pendiente'), (6, 'Aprobado'), (7, 'Rechazado')], db_column='proy_estado', default=1)),
                ('proy_visible', models.IntegerField(db_column='proy_visible', default=1)),
                ('proy_creado', models.DateTimeField(auto_now_add=True, db_column='proy_creado')),
                ('proy_actualizado', models.DateTimeField(auto_now=True, db_column='proy_actualizado')),
                ('proy_lugar', models.CharField(db_column='proy_lugar', default='', max_length=255)),
                ('proy_prioridad', models.IntegerField(choices=[(1, 'Normal'), (2, 'Importante'), (3, 'Muy Importante')], db_column='proy_prioridad', default=1)),
                ('proy_fecha_inicio_estimada', models.DateField(blank=True, db_column='proy_fecha_inicio_estimada', null=True)),
                ('proy_tipo_denuncia', models.CharField(blank=True, db_column='proy_tipo_denuncia', default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'Proyecto',
                'ordering': ['-proy_creado'],
            },
        ),
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_denuncias',
            },
        ),
        migrations.CreateModel(
            name='ProyectoArchivosModel',
            fields=[
                ('proar_id', models.AutoField(db_column='proar_id', primary_key=True, serialize=False)),
                ('proar_tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('video', 'Video'), ('plano', 'Plano'), ('otro', 'Otro')], db_column='proar_tipo', max_length=50)),
                ('proar_contenido_tipo', models.CharField(db_column='proar_contenido_tipo', max_length=100)),
                ('proar_mime', models.CharField(db_column='proar_mime', max_length=100)),
                ('proar_nombre_archivo', models.CharField(db_column='proar_nombre_archivo', max_length=255)),
                ('proar_ruta', models.CharField(db_column='proar_ruta', max_length=500)),
                ('proar_visible', models.IntegerField(db_column='proar_visible', default=1)),
                ('proar_creado', models.DateTimeField(auto_now_add=True, db_column='proar_creado')),
                ('proar_actualizado', models.DateTimeField(auto_now=True, db_column='proar_actualizado')),
                ('proy_id', models.ForeignKey(db_column='proy_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reports.proyectomodel')),
            ],
            options={
                'verbose_name': 'Archivo de Proyecto',
                'verbose_name_plural': 'Archivos de Proyectos',
                'db_table': 'Proyecto_archivos',
                'ordering': ['-proar_creado'],
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('ubicacion', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('urgencia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=7, default=0.0, help_text='Coordenada de latitud (-90 a 90)', max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, default=0.0, help_text='Coordenada de longitud (-180 a 180)', max_digits=10, verbose_name='Longitud')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ciudad')),
                ('denuncia_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.denunciaestado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='entities.usuario')),
                ('tipo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.tipodenuncia')),
            ],
            options={
                'db_table': 'reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='denu_id',
            field=models.ForeignKey(db_column='denu_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='reports.reportmodel'),
        ),
        migrations.CreateModel(
            name='ReportArchivo',
            fields=[
                ('dear_id', models.AutoField(primary_key=True, serialize=False)),
                ('dear_nombre', models.CharField(help_text='Nombre del archivo: foto_001.jpg', max_length=255)),
                ('dear_extension', models.CharField(help_text='Extensión del archivo: jpg, png, mp4', max_length=10)),
                ('dear_es_principal', models.BooleanField(default=False, help_text='1 = principal, 0 = no')),
                ('dear_orden', models.IntegerField(default=0, help_text='Orden de visualización: 0, 1, 2, 3...')),
                ('dear_creado', models.DateTimeField(auto_now_add=True)),
                ('dear_actualizado', models.DateTimeField(auto_now=True)),
                ('denu', models.ForeignKey(db_column='denu_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reports.reportmodel')),
            ],
            options={
                'verbose_name': 'Archivo de Reporte',
                'verbose_name_plural': 'Archivos de Reportes',
                'db_table': 'reportes_archivos',
                'ordering': ['dear_orden', 'dear_creado'],
                'indexes': [models.Index(fields=['denu_id'], name='reportes_ar_denu_id_672ea1_idx'), models.Index(fields=['dear_extension'], name='reportes_ar_dear_ex_42dc4a_idx'), models.Index(fields=['dear_es_principal'], name='reportes_ar_dear_es_0b71da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=10, verbose_name='Tipo')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='entities.usuario', verbose_name='Usuario')),
                ('denuncia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='reports.reportmodel', verbose_name='Reporte relacionado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'), models.Index(fields=['-fecha_creacion'], name='notificacio_fecha_c_5e3141_idx')],
            },
        ),
    ]
