# Generated by Django 5.2.6 on 2025-10-20 22:49

import django.db.models.deletion
import django.utils.timezone
import reports.models.report_archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportarchivo',
            options={'ordering': ['orden', 'fecha_subida'], 'verbose_name': 'Archivo de Reporte', 'verbose_name_plural': 'Archivos de Reportes'},
        ),
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RemoveIndex(
            model_name='reportarchivo',
            name='reportes_ar_denu_id_672ea1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportarchivo',
            name='reportes_ar_dear_ex_42dc4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportarchivo',
            name='reportes_ar_dear_es_0b71da_idx',
        ),
        migrations.RenameField(
            model_name='reportarchivo',
            old_name='dear_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_actualizado',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_creado',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_es_principal',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_extension',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_nombre',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='dear_orden',
        ),
        migrations.RemoveField(
            model_name='reportarchivo',
            name='denu',
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el archivo está activo', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='alto',
            field=models.PositiveIntegerField(blank=True, help_text='Alto en píxeles (para imágenes y videos)', null=True, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='ancho',
            field=models.PositiveIntegerField(blank=True, help_text='Ancho en píxeles (para imágenes y videos)', null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='archivo',
            field=models.FileField(default=1, help_text='Archivo subido (imagen, video o documento)', max_length=200, upload_to=reports.models.report_archivos.upload_to_report_files, verbose_name='Archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='duracion_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en segundos (solo para videos)', null=True, verbose_name='Duración en segundos'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Indica si este es el archivo principal del reporte', verbose_name='Es principal'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='extension',
            field=models.CharField(default='jpg', help_text='Extensión del archivo sin el punto (jpg, png, mp4, etc.)', max_length=10, verbose_name='Extensión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='fecha_actualizada',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de subida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Tipo MIME del archivo (image/jpeg, video/mp4, etc.)', max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='nombre_original',
            field=models.CharField(default='lol', help_text='Nombre original del archivo al momento de la subida', max_length=255, verbose_name='Nombre original'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización del archivo', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='reporte',
            field=models.ForeignKey(default=1, help_text='Reporte al que pertenece este archivo', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reports.reportmodel', verbose_name='Reporte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='tamaño_bytes',
            field=models.PositiveBigIntegerField(default=0, help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en bytes'),
        ),
        migrations.AddField(
            model_name='reportarchivo',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento')], default='imagen', max_length=20, verbose_name='Tipo de archivo'),
        ),
        migrations.AddIndex(
            model_name='reportarchivo',
            index=models.Index(fields=['reporte', 'activo'], name='report_arch_reporte_bd76d9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportarchivo',
            index=models.Index(fields=['tipo_archivo'], name='report_arch_tipo_ar_165495_idx'),
        ),
        migrations.AddIndex(
            model_name='reportarchivo',
            index=models.Index(fields=['es_principal'], name='report_arch_es_prin_79fdec_idx'),
        ),
        migrations.AddIndex(
            model_name='reportarchivo',
            index=models.Index(fields=['fecha_subida'], name='report_arch_fecha_s_ddd8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['usuario', 'visible'], name='reportes_usuario_596e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['fecha_creacion'], name='reportes_fecha_c_2cef5a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['urgencia'], name='reportes_urgenci_a25701_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmodel',
            index=models.Index(fields=['denuncia_estado'], name='reportes_denunci_e86780_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportarchivo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('reporte',), name='unique_principal_per_reporte'),
        ),
        migrations.AlterModelTable(
            name='reportarchivo',
            table='report_archivos',
        ),
    ]
