# Generated by Django 5.2.6 on 2025-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
