# Generated by Django 5.2.7 on 2025-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_create_comentario_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioreporte',
            name='comment_visible',
            field=models.BooleanField(default=True, help_text='Indica si el comentario es visible para los usuarios', verbose_name='Comentario visible'),
        ),
    ]
