# Generated by Django 5.2.7 on 2025-10-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_create_seguimiento_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoarchivosmodel',
            name='proy_id',
        ),
        migrations.RemoveField(
            model_name='proyectomodel',
            name='denu_id',
        ),
        migrations.RenameIndex(
            model_name='seguimientoreporte',
            new_name='reports_seg_usuario_5bb851_idx',
            old_name='seguimiento_usuario_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='seguimientoreporte',
            new_name='reports_seg_reporte_4db195_idx',
            old_name='seguimiento_reporte_idx',
        ),
        migrations.AlterModelTable(
            name='seguimientoreporte',
            table=None,
        ),
        migrations.DeleteModel(
            name='ProyectoArchivosModel',
        ),
        migrations.DeleteModel(
            name='ProyectoModel',
        ),
    ]
