# Generated by Django 5.2.6 on 2025-10-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_ciudad_id_alter_denunciaestado_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
