# Generated by Django 5.2.7 on 2025-10-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_proyectoarchivosmodel_proy_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seguimientoreporte',
            new_name='seguimiento_usuario_f52b05_idx',
            old_name='reports_seg_usuario_5bb851_idx',
        ),
        migrations.RenameIndex(
            model_name='seguimientoreporte',
            new_name='seguimiento_reporte_7332d6_idx',
            old_name='reports_seg_reporte_4db195_idx',
        ),
        migrations.AlterModelTable(
            name='seguimientoreporte',
            table='seguimiento_reporte',
        ),
    ]
