# Generated by Django 5.2.6 on 2025-10-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_usuario_reportmodel_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
