# Generated by Django 5.2.7 on 2025-10-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
        ('reports', '0005_rename_seguimiento_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoReporte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del voto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='reports.reportmodel', verbose_name='Reporte')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='votos_reportes', to='entities.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto de Reporte',
                'verbose_name_plural': 'Votos de Reportes',
                'db_table': 'voto_reporte',
                'ordering': ['-fecha_voto'],
                'indexes': [models.Index(fields=['usuario', 'fecha_voto'], name='voto_report_usuario_29e689_idx'), models.Index(fields=['reporte'], name='voto_report_reporte_2db064_idx')],
                'unique_together': {('usuario', 'reporte')},
            },
        ),
    ]
