# Generated by Django 5.2.6 on 2025-10-20 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
        ('reports', '0006_create_voto_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREATE', 'Creado'), ('UPDATE', 'Actualizado'), ('DELETE', 'Eliminado'), ('STATUS_CHANGE', 'Cambio de Estado'), ('URGENCY_CHANGE', 'Cambio de Urgencia'), ('IMAGE_ADD', 'Imagen Agregada'), ('IMAGE_DELETE', 'Imagen Eliminada')], max_length=20, verbose_name='Acción')),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reports.reportmodel', verbose_name='Reporte')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_reportes', to='entities.usuario', verbose_name='Usuario que realizó la acción')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'db_table': 'report_history',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['reporte', '-fecha'], name='report_hist_reporte_996e1f_idx'), models.Index(fields=['usuario'], name='report_hist_usuario_2a390d_idx')],
            },
        ),
    ]
