# Generated by Django 5.2.6 on 2025-10-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_usuario_usua_id'),
        ('reports', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='entities.usuario', verbose_name='Usuario'),
        ),
    ]
